-- MySQL Script generated by MySQL Workbench
-- Fri Apr 12 19:35:50 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_pucvendas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_pucvendas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_pucvendas` DEFAULT CHARACTER SET utf8 ;
USE `db_pucvendas` ;

-- -----------------------------------------------------
-- Table `db_pucvendas`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pucvendas`.`usuario` (
  `id` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pucvendas`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pucvendas`.`categoria` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pucvendas`.`fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pucvendas`.`fornecedor` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `url` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pucvendas`.`status_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pucvendas`.`status_compra` (
  `id` INT NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pucvendas`.`compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pucvendas`.`compras` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `valor` DOUBLE NULL,
  `status_compra_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_compras_status_compra_idx` (`status_compra_id` ASC) VISIBLE,
  INDEX `fk_compras_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_compras_status_compra`
    FOREIGN KEY (`status_compra_id`)
    REFERENCES `db_pucvendas`.`status_compra` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compras_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `db_pucvendas`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pucvendas`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pucvendas`.`produto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `image_path` VARCHAR(256) NULL,
  `nome` VARCHAR(100) NOT NULL,
  `data_validade` DATE NULL,
  `descricao` VARCHAR(256) NULL,
  `preco` DOUBLE NOT NULL,
  `quantidade` INT NOT NULL,
  `codigo` INT NOT NULL,
  `ativo` CHAR(1) NOT NULL,
  `categoria_id` INT NOT NULL,
  `fornecedor_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_produto_categoria1_idx` (`categoria_id` ASC) VISIBLE,
  INDEX `fk_produto_fornecedor1_idx` (`fornecedor_id` ASC) VISIBLE,
  CONSTRAINT `fk_produto_categoria1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `db_pucvendas`.`categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_fornecedor1`
    FOREIGN KEY (`fornecedor_id`)
    REFERENCES `db_pucvendas`.`fornecedor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pucvendas`.`compras_produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pucvendas`.`compras_produtos` (
  `produtos_id` INT NOT NULL,
  `compras_id` INT NOT NULL,
  INDEX `fk_produto_has_compras_compras1_idx` (`compras_id` ASC) VISIBLE,
  INDEX `fk_produto_has_compras_produto1_idx` (`produtos_id` ASC) VISIBLE,
  CONSTRAINT `fk_produto_has_compras_produto1`
    FOREIGN KEY (`produtos_id`)
    REFERENCES `db_pucvendas`.`produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_has_compras_compras1`
    FOREIGN KEY (`compras_id`)
    REFERENCES `db_pucvendas`.`compras` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;




INSERT INTO categoria VALUES (1,'Bebidas'),(2,'Livros'),(3,'Relogio');

INSERT INTO usuario VALUES (1,'werickzim@gmail.com','werick','123');

INSERT INTO fornecedor VALUES (1,'pucvendas loja','http://localhost:9000');

INSERT INTO status_compra VALUES (1,'Pedido foi recebido pelo fornecedor','Recebido'),(2,'Pedido foi recusado pelo fornecedor','Recusado'),(3,'Pedido foi embalado pelo fornecedor e encontra-se pronto para expedição','Embalado'),(4,'Pedido está sendo transportado pelo fornecedor','Transportando'),(5,'Pedido foi entregue ao cliente pelo fornecedor','Entregue');

INSERT INTO produto VALUES (1,'http://localhost:8080/imagens/produtos/whisky-johnnie-walker-black-label_id1.jpg','Whisky Johnnie Walker Black Label 1l',1,1,'2020-01-22','Johnnie Walker Black Label é um verdadeiro ícone.',139,100,1,'1'),(2,'http://localhost:8080/imagens/produtos/whiskey-jack-daniels-375ml.jpg','Whiskey Jack Daniel´s 375ml',1,1,'2020-12-31','Whiskey Jack Daniel´s 375ml',90,100,2,'1'),(3,'http://localhost:8080/imagens/produtos/chopp-da-heineken-5-litros-barril.jpg','Chopp Da Heineken 5 Litros Barril',1,1,'2020-12-31','Heineken é uma cerveja super premium puro malte, elaborada com ingredientes 100% naturais e sem adição de conservantes. ',97,100,3,'0'),(4,'http://localhost:8080/imagens/produtos/livro-java-guia-do-programador.jpg','Livro Java Guia Do Programador - 3ª Edição Novatec Editora',2,1,'2020-12-31','O livro Java – Guia do Programador abrange o conteúdo essencial para as certificações Oracle Certified Associate e Oracle Certified Professional para Java SE 5, SE 6, SE 7 e SE 8.',119,100,4,'1'),(5,'http://localhost:8080/imagens/produtos/livro-angular.jpg','Livro Angularjs',2,1,'2020-12-31','AngularJS é um framework JavaScript revolucionário, mantido por um time de engenheiros Google.',53,100,5,'1'),(6,'http://localhost:8080/imagens/produtos/relogio-r-submariner-black-silver.jpg','Relógio R. Submariner Black Silver Superior',3,1,'2020-12-31','Relógio de Grife Luxuosa Série Submariner Black Silver Superior ( Construido em Liga de Aço Inoxidável) - Relógio com todos os detalhes e características gravadas.',549,100,6,'1'),(7,'http://localhost:8080/imagens/produtos/relogio-masculino-catraca-azul-vermelho.jpg','Relógio Masculino Catraca Azul Vermelho Autómatico Aço Inox',3,1,'2020-12-31','Relógio Masculino Catraca Azul Vermelho Autómatico Aço Inox',629,100,7,'1');

INSERT INTO compras VALUES (1,'2019-03-25',229,1,1);

INSERT INTO compras_produtos VALUES (1,1),(1,2);






